// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxGz6M63jWFCGwRdTc8egXx9L3m4sGfQE',
    appId: '1:569889070377:web:bdca3d87240262745b2b38',
    messagingSenderId: '569889070377',
    projectId: 'devsapmorning',
    authDomain: 'devsapmorning.firebaseapp.com',
    storageBucket: 'devsapmorning.appspot.com',
    measurementId: 'G-YZM92250TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhoDryZ69PzpcnTc9JAlWZt_m0m8V6AW8',
    appId: '1:569889070377:android:34a743d2a99dc93c5b2b38',
    messagingSenderId: '569889070377',
    projectId: 'devsapmorning',
    storageBucket: 'devsapmorning.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfBxfG8oqRn_8f3hiWWzAmHNt6-wmKLxw',
    appId: '1:569889070377:ios:ac610315aefac5345b2b38',
    messagingSenderId: '569889070377',
    projectId: 'devsapmorning',
    storageBucket: 'devsapmorning.appspot.com',
    iosClientId: '569889070377-3raqk9lge1ojv7vu7craloqr0rk10ie0.apps.googleusercontent.com',
    iosBundleId: 'jp.tama.ritest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfBxfG8oqRn_8f3hiWWzAmHNt6-wmKLxw',
    appId: '1:569889070377:ios:ac610315aefac5345b2b38',
    messagingSenderId: '569889070377',
    projectId: 'devsapmorning',
    storageBucket: 'devsapmorning.appspot.com',
    iosClientId: '569889070377-3raqk9lge1ojv7vu7craloqr0rk10ie0.apps.googleusercontent.com',
    iosBundleId: 'jp.tama.ritest',
  );
}
